export const storeData = [
  {
    id: 1,
    image: "/assets/images/fur-1.png",
    des: "Trenton modular sofa_3",
    price: "Rs.25,000.00",
  },
  {
    id: 2,
    image: "/assets/images/fur-2.png",
    des: "Granite dining table with dining chair",
    price: "Rs.25,000.00",
  },
  {
    id: 3,
    image: "/assets/images/fur-3.png",
    des: "Outdoor bar table and stool",
    price: "Rs.25,000.00",
  },
  {
    id: 4,
    image: "/assets/images/fur-4.png",
    des: "Plain console with teak mirror",
    price: "Rs.25,000.00",
  },
  {
    id: 5,
    image: "/assets/images/fur-5.png",
    des: "Grain coffee table",
    price: "Rs.15,000.00",
  },
  {
    id: 6,
    image: "/assets/images/fur-6.png",
    des: "Kent coffee table",
    price: "Rs.225,000.00",
  },
  {
    id: 7,
    image: "/assets/images/fur-7.png",
    des: "Round coffee table_color 2",
    price: "Rs.215,000.00",
  },
  {
    id: 8,
    image: "/assets/images/fur-8.png",
    des: "Reclaimed teak coffee table",
    price: "Rs.25,200.00",
  },
  {
    id: 9,
    image: "/assets/images/fur-9.png",
    des: "Plain console_",
    price: "Rs.258,800.00",
  },
  {
    id: 10,
    image: "/assets/images/fur-10.png",
    des: "Reclaimed teak Sideboard",
    price: "Rs.20,000.00",
  },
  {
    id: 11,
    image: "/assets/images/fur-11.png",
    des: "SJP_0825",
    price: "Rs.200,000.00",
  },
  {
    id: 12,
    image: "/assets/images/fur-12.png",
    des: "shop__card__content",
    price: "Rs.100,000.00",
  },
  {
    id: 13,
    image: "/assets/images/fur-13.png",
    des: "Granite square side table",
    price: "Rs.258,000.00",
  },
  {
    id: 14,
    image: "/assets/images/fur-14.png",
    des: "Asgaard sofa",
    price: "Rs.250,000.00",
  },
  {
    id: 15,
    image: "/assets/images/fur-15.png",
    des: "Maya sofa three seater",
    price: "Rs.115,000.00",
  },
  {
    id: 16,
    image: "/assets/images/fur-16.png",
    des: "Outdoor sofa set",
    price: "Rs.244,000.00",
  },
  // {
  //   id: 17,
  //   image: fur17,
  //   des: "Outdoor lamp set",
  //   price: "Rs.24,000.00",
  // },
  // {
  //   id: 18,
  //   image: fur18,
  //   des: "Indoor sofa set",
  //   price: "Rs.264,000.00",
  // },
  // {
  //   id: 19,
  //   image: fur19,
  //   des: "Deep sit",
  //   price: "Rs.300,000.00",
  // },
  // {
  //   id: 20,
  //   image: fur20,
  //   des: "sofa set",
  //   price: "Rs.277,000.00",
  // },
  // {
  //   id: 21,
  //   image: fur21,
  //   des: "Vase",
  //   price: "Rs.34,000.00",
  // },
  // {
  //   id: 22,
  //   image: fur22,
  //   des: "Wall Shelf ",
  //   price: "Rs.64,000.00",
  // },
  // {
  //   id: 23,
  //   image: fur23,
  //   des: "Work space table",
  //   price: "Rs.54,000.00",
  // },
  // {
  //   id: 24,
  //   image: fur24,
  //   des: "King size Sofa",
  //   price: "Rs.200,000.00",
  // },
  // {
  //   id: 25,
  //   image: fur25,
  //   des: "bed side chair",
  //   price: "Rs.24,000.00",
  // },
  // {
  //   id: 26,
  //   image: fur26,
  //   des: "vase table",
  //   price: "Rs.20,000.00",
  // },
  // {
  //   id: 27,
  //   image: fur27,
  //   des: "wall frame and vase",
  //   price: "Rs.50,000.00",
  // },
  // {
  //   id: 28,
  //   image: fur28,
  //   des: "Kitchen Flower Shelf",
  //   price: "Rs.21,000.00",
  // },
  // {
  //   id: 29,
  //   image: fur29,
  //   des: "bed side table",
  //   price: "Rs.34,000.00",
  // },
];
